### ISSUE TITLE
Issue with ZIBO and SimVim when activating APU Bleeds

### ISSUE THREAD

**Issue by Gunduran** [leecbaker/datareftool#71] opened 2021-01-24 14:54 UTC
Hello,
I'm running the latest X-Plane with ZIBO and have some smaller pieces that I steer using SIMVIM.
I also use XChecklist and FirstOfficer to automate a bit. 

Due to these optimizations I found an issue when DataRef is open and I turn on the APU Bleed. It causes a CTD. But it happens also, if I come without FirstOfficer to this point... 
In the logfile it looks like that it might be caused from SimVim but  If I have turned off DataRefTool it works fine. So I assume, that the issue is caused by DataRefTool. 

If I could help you with debugging, please let me know how to do... I know that it might not help, but I've added the log.txt.
[Log.txt](https://github.com/leecbaker/datareftool/files/5862470/Log.txt)

**Comment by leecbaker** [comment] 2021-01-26 06:18
Hi Gunduran,

From looking at the log file, this seems like an issue with SimVim. I would contact the developer, and see if they can help with this issue.

Because DRT interacts with all installed plugins, it tends to expose bugs in other plugins quite often. I suspect that's what has happened here (though I don't know for sure). I don't use SimVim, nor do I fly the Zibo very often, so I can't really help.

I'd recommend removing all plugins, and try to replicate the crash. Gradually add back the plugins one by one until the crash happens again, and that should help you identify exactly which plugin is causing the crash.

If the CTD only happens when DRT is installed, I would send the following link when you contact the developer; it might help them debug: https://datareftool.com/#faq-using-drt-causes-x-plane-to-crash

Hope this helps. I'm going to close this issue since it seems to be caused by another plugin and not DRT. If for some reason you discover that this isn't the case, please reopen this issue.

**Closed by leecbaker** 2021-01-26 06:18 UTC
