### ISSUE TITLE
X-Plane crashes

### ISSUE THREAD

**Issue by Clamb94** [leecbaker/datareftool#30] opened 2018-06-20 06:12 UTC
Hi, 
I'm expreriencing a really strange issue. 
Sometimes, X-Plane will crash and I won't be able to launch X-Plane anymore. The log.txt shows the following:
`--=={This application has crashed because of the plugin: DataRefTool_2018_06_06/win.xpl}==--`
Propalby not really helpful, I know. Is there any other kind of crashlog available? 

After removing DataRefTool from the plugins, X-Plane works just fine again. However, after a while I can add it again to the plugins and it works again. But it seems to be more or less random. Sometimes it works again, sometimes it doesn't. Really strange. 
It's not easily reproduceable.

I'm using release 2018_06_06. Windows 10. X-Plane 11.21.

Edit: Fully crashlog: https://pastebin.com/2YK2Sq4b

Edit2: Just tested the release "2017_09_10". This one seems to be working perfectly.

**Comment by leecbaker** [comment] 2018-07-01 10:03
@Clamb94 Sorry to hear that it's crashing. I really have no idea what's causing this. Unfortunately I can't determine much from the crash log.

Some crashes may be caused by bugs in DRT (sorry!). Some crashes can be caused by other plugins, and they still show up in the log as attributed to DRT. Here's how that usually looks:

- As part of running the plugin system, X-Plane calls the DRT plugin (through flight loop `update_dr_callback()`)
- DRT asks X-Plane to read a dataref provided by another plugin. (Function `XPLMGetDatax()`)
- X-Plane asks the plugin for the dataref's value (by calling the callbacks provided to `XPLMRegisterDataAccessor()` in the other plugin)
- The other plugin crashes because of a bug in the other plugin.
- X-Plane sees that the plugin has crashed. It knows that it called DRT's flight loop, so that must be the plugin that crashes, and misattributes the crash.

Removing the other plugin or aircraft is often the best way to separate crashes caused by other plugins vs. crashes caused by bugs in DRT.

**Comment by leecbaker** [comment] 2018-07-01 10:04
Now that I re-read your bug report- since there is no crash when using an older release of DRT, it sounds like this is just a bug in the newer version of DRT. I wonder what it is?

**Comment by leecbaker** [comment] 2018-07-04 17:58
@Clamb94 That's good to hear. I'm going to close this bug report, but if you have the same problem again, feel free to re-open it.

**Closed by leecbaker** 2018-07-04 17:58 UTC
